# Generated by Django 6.0.4 on 2026-04-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_ofensora', models.GenericIPAddressField()),
                ('tipo_ataque', models.CharField(choices=[('SQLI', 'Inyección SQL'), ('XSS', 'Cross-Site Scripting'), ('BF', 'Fuerza Bruta'), ('SUSP', 'Actividad Sospechosa')], max_length=5)),
                ('payload_malicioso', models.TextField()),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('bloqueado', models.BooleanField(default=True)),
            ],
        ),
    ]
