# Generated by Django 6.0.4 on 2026-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('lote', models.CharField(default='LOTE-001', max_length=50)),
                ('temperatura_optima', models.CharField(default='4°C', max_length=20)),
            ],
        ),
    ]
