# Generated by Django 6.0.4 on 2026-04-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('LECHE', 'Leche'), ('QUESO', 'Queso'), ('CREMA', 'Crema'), ('YOGURT', 'Yogurt')], default='QUESO', max_length=20),
        ),
    ]
